services:
  - type: web
    name: english-battle-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://english-battle-kappa.vercel.app
      - key: PORT
        value: 10000
